name: Backend Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore backend/BackendApi.csproj backend/BackendApi.Tests/BackendApi.Tests.csproj
      - name: Build
        run: dotnet build backend/BackendApi.csproj backend/BackendApi.Tests/BackendApi.Tests.csproj --configuration Release --no-restore
      - name: Test
        run: dotnet test backend/BackendApi.Tests/BackendApi.Tests.csproj --no-build --verbosity normal
