name: Terraform Destroy

on:
  workflow_dispatch:
    # Allows manual trigger from the Actions tab

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: |
          terraform init \
            -backend-config="bucket=ap-southeast-2-shaun-terraform-workflow" \
            -backend-config="key=state/terraform.tfstate" \
            -backend-config="region=ap-southeast-2"

      - name: Get ECR Repository URI
        id: ecr-uri
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          REPO_URI="$ACCOUNT_ID.dkr.ecr.ap-southeast-2.amazonaws.com/auth-learning-api:latest"
          echo "repo_uri=$REPO_URI" >> "$GITHUB_OUTPUT"

      - name: Terraform Destroy
        working-directory: terraform
        run: |
          terraform destroy -auto-approve 
            -var="ecr_image_uri=${{ steps.ecr-uri.outputs.repo_uri }}" 
            -var="cert_password=${{ secrets.CERT_PASSWORD }}"
        env:
          TF_WORKSPACE: production

